language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
install:
  - npm install
  - npm install -g codecov  
script:
  - npm run test:coverage 
  - codecov